language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: HuVcSKI+DnARoIe8J+uXtXhsdgNZC2kqoTOfJCLa6R6JbSuMY/+WwYH3RWYVJIlUvVnwX2QO6wvm1IuxpMWav7MlIHw75wyebR5jFYEUY26uJ51jwy+gjHB0R5kJ3VIP9UgbO78X0zsbQS3rZNFcRoO+Smu4cr+vpCdBfnN+y8Q=
  app: pghrb-20131003-travis-talk
  on:
    repo: meatballhat/pghrb-20131003-travis-talk
